[package]
name = "live-poly-trans"
version = "0.1.0"
description = "Realtime multilingual transcription and translation"
authors = ["staticWagomU"]
edition = "2021"

[lib]
name = "live_poly_trans_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1"
cpal = "0.18.1"
lpt-core = { path = "../crates/lpt-core" }
lpt-whisper = { path = "../crates/lpt-whisper" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
